export const category = [
	"Jewelry",
	"Ladies Apparels",
	"Men Apparels",
	"Footwear",
	"Perfume",
	"Saree",
	"Dress Material",
	"Kids Wear",
	"Toys",
	"Beauty Products",
	"Home Decor",
	"Gifts",
	"Home and kitchen Appliance",
	"Ladies Purse",
	"Men Belts and Wallets",
	"Mobile Accessories",
	"Packed Food",
	"Travel Bags",
	"Furniture",
	"Lingerie",
	"Carpets",
	"Shawls and Scarfs",
	"Handmade",
	"Handicraft",
	"Unique Products",
];
